"""BA II Plus parity vectors derived from the TI BA II Plus guidebook.

Each case records the physical-calculator keystrokes that produce the expected
display.  The simulator result is generated by the shared browser math core.
"""

from __future__ import annotations

import json
from pathlib import Path
import shutil
import subprocess

import pytest


CORE = Path(__file__).resolve().parents[1] / "assets" / "financial_calculator_core.js"
CALCULATOR_UI = Path(__file__).resolve().parents[1] / "src" / "financial_calculator.py"


def simulator_result(expression: str):
    if not shutil.which("node"):
        pytest.skip("Node.js is required for calculator parity checks")
    script = f"const m=require({json.dumps(str(CORE))}); console.log(JSON.stringify({expression}));"
    result = subprocess.run(["node", "-e", script], check=True, text=True, capture_output=True)
    return json.loads(result.stdout)


PARITY_CASES = [
    ("AOS order of operations", "2nd FORMAT; select AOS; 3 + 2 × 4 =", "m.evaluateExpression([3,'+',2,'×',4])", 11.0),
    ("percentage add-on", "498 + 7 % =", "498+m.percentOperand(498,'+',7)", 532.86),
    ("combination", "52 2nd nCr 5 =", "m.combinations(52,5)", 2598960.0),
    ("TVM present value", "2nd CLR TVM; 10 N; 8 I/Y; 1000 FV; CPT PV", "m.solveTvm('pv',{n:10,iy:8,pv:0,pmt:0,fv:1000,py:1,cy:1,begin:false})", -463.1934880847),
    ("TVM future value", "2nd CLR TVM; 5 N; 6 I/Y; 1000 +/- PV; CPT FV", "m.solveTvm('fv',{n:5,iy:6,pv:-1000,pmt:0,fv:0,py:1,cy:1,begin:false})", 1338.2255776),
    ("annuity payment", "2nd CLR TVM; 360 N; 6 I/Y; 300000 PV; CPT PMT", "m.solveTvm('pmt',{n:360,iy:6,pv:300000,pmt:0,fv:0,py:12,cy:12,begin:false})", -1798.6515754582),
    ("solve I/Y", "2nd CLR TVM; 2 N; 1000 +/- PV; 1210 FV; CPT I/Y", "m.solveTvm('iy',{n:2,iy:0,pv:-1000,pmt:0,fv:1210,py:1,cy:1,begin:false})", 10.0),
    ("END annuity", "2nd CLR TVM; 3 N; 10 I/Y; 100 +/- PMT; CPT FV", "m.solveTvm('fv',{n:3,iy:10,pv:0,pmt:-100,fv:0,py:1,cy:1,begin:false})", 331.0),
    ("BGN annuity", "2nd PMT; 2nd ENTER; 2nd QUIT; CPT FV", "m.solveTvm('fv',{n:3,iy:10,pv:0,pmt:-100,fv:0,py:1,cy:1,begin:true})", 364.1),
    ("non-annual P/Y", "2nd I/Y; 12 ENTER; 360 N; 6 I/Y; 300000 PV; CPT PMT", "m.solveTvm('pmt',{n:360,iy:6,pv:300000,pmt:0,fv:0,py:12,cy:12,begin:false})", -1798.6515754582),
    ("uneven cash flows NPV", "CF; 7000 +/- ENTER; 3000 ENTER; 4000 ENTER; 5000 ENTER; 4 ENTER; NPV; 20 ENTER; down; CPT", "m.npv(20,-7000,[{value:3000,frequency:1},{value:4000,frequency:1},{value:5000,frequency:4}])", 7266.4394718793),
    ("cash-flow frequency", "CF; down; 5000 ENTER; down; 4 ENTER", "m.expandCashFlows([{value:5000,frequency:4}]).length", 4.0),
    ("IRR", "CF data as above; IRR; CPT", "m.irr(-7000,[{value:3000,frequency:1},{value:4000,frequency:1},{value:5000,frequency:4}])", 52.7053745072),
    ("bond price", "2nd BOND; enter known values; down to PRI; CPT", "m.bondPrice(100,5,6,10,2)", 92.5612625698),
    ("bond yield", "2nd BOND; enter PRI 92.56126257; down to YLD; CPT", "m.bondYield(92.56126256977225,100,5,10,2)", 6.0),
    ("amortization balance", "TVM loan values; 2nd AMORT; 1 ENTER; down; 12 ENTER; down to BAL", "m.amortization({iy:6,py:12,cy:12,pv:100000,pmt:-599.5505251527569,begin:false},1,12).balance", 98771.9882877231),
    ("one-variable statistics", "2nd DATA; enter 1,2,3; 2nd STAT; choose 1-V; down to mean", "m.statistics([{x:1},{x:2},{x:3}],true).meanX", 2.0),
    ("interest conversion", "2nd ICONV; 12 ENTER; down to EFF; down; 12 ENTER C/Y; up; CPT", "m.nominalToEffective(12,12)", 12.6825030132),
    ("date calculation", "2nd DATE; 1.0124 ENTER; down; 12.3124 ENTER; down to DBD; CPT", "m.daysBetween('2024-01-01','2024-12-31','ACT')", 365.0),
    ("profit margin", "2nd PROFIT; 100 CST; 125 SEL; down to MAR; CPT", "m.profitMargin('margin',{cost:100,sell:125,margin:0})", 20.0),
    ("break-even quantity", "2nd BRKEVN; 10000 FC; 4 VC; 9 P; 0 PFT; down to Q; CPT", "m.breakEven('quantity',{fixed:10000,variable:4,price:9,quantity:0,profit:0})", 2000.0),
    ("straight-line depreciation", "2nd DEPR; SL SET; 10 LIF; 100000 CST; 10000 SAL; 1 YR; down to DEP", "m.straightLineDepreciation(100000,10000,10,1).depreciation", 9000.0),
]


@pytest.mark.parametrize("name,keystrokes,expression,expected", PARITY_CASES, ids=[case[0] for case in PARITY_CASES])
def test_ba2_plus_reference_vectors(name, keystrokes, expression, expected):
    """The case name and keystrokes are retained in pytest's test ID/report."""
    assert keystrokes
    assert simulator_result(expression) == pytest.approx(expected, rel=1e-9, abs=1e-8)


def test_clear_sequences_really_zero_the_registers():
    source = CALCULATOR_UI.read_text(encoding="utf-8")
    assert "S.tvm.n=0;S.tvm.iy=0;S.tvm.pv=0;S.tvm.pmt=0;S.tvm.fv=0" in source
    assert "S.cash={cf0:0,groups:[]};S.npvRate=0" in source
    assert "delete state.history" in source
